import Head from "next/head";
import { FC, ReactNode } from "react";

import { useFetchMe } from "src/hooks/useFetchMe";

import { Header } from "./components/header";

import styles from "./MainLayout.module.css";

export interface MainLayoutProps {
  children: ReactNode;
}
export const MainLayout: FC<MainLayoutProps> = ({ children }) => {
  useFetchMe();

  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header/>
        <div className={styles.content}>
          {children}
        </div>
      </div>
    </>
  );
};

MainLayout.displayName = "MainLayoutProps";
