import { ChoiceValue } from "../../../models/choices";

export const playOptionsStub = [
  [ChoiceValue.ROCK, ChoiceValue.ROCK, 0],
  [ChoiceValue.ROCK, ChoiceValue.PAPER, -1],
  [ChoiceValue.ROCK, ChoiceValue.SCISSORS, 1],
  [ChoiceValue.ROCK, ChoiceValue.SPOCK, -1],
  [ChoiceValue.ROCK, ChoiceValue.LIZARD, 1],
  [ChoiceValue.PAPER, ChoiceValue.ROCK, 1],
  [ChoiceValue.PAPER, ChoiceValue.PAPER, 0],
  [ChoiceValue.PAPER, ChoiceValue.SCISSORS, -1],
  [ChoiceValue.PAPER, ChoiceValue.SPOCK, 1],
  [ChoiceValue.PAPER, ChoiceValue.LIZARD, -1],
  [ChoiceValue.SCISSORS, ChoiceValue.ROCK, -1],
  [ChoiceValue.SCISSORS, ChoiceValue.PAPER, 1],
  [ChoiceValue.SCISSORS, ChoiceValue.SCISSORS, 0],
  [ChoiceValue.SCISSORS, ChoiceValue.SPOCK, -1],
  [ChoiceValue.SCISSORS, ChoiceValue.LIZARD, 1],
  [ChoiceValue.SPOCK, ChoiceValue.ROCK, 1],
  [ChoiceValue.SPOCK, ChoiceValue.PAPER, -1],
  [ChoiceValue.SPOCK, ChoiceValue.SCISSORS, 1],
  [ChoiceValue.SPOCK, ChoiceValue.SPOCK, 0],
  [ChoiceValue.SPOCK, ChoiceValue.LIZARD, -1],
  [ChoiceValue.LIZARD, ChoiceValue.ROCK, -1],
  [ChoiceValue.LIZARD, ChoiceValue.PAPER, 1],
  [ChoiceValue.LIZARD, ChoiceValue.SCISSORS, -1],
  [ChoiceValue.LIZARD, ChoiceValue.SPOCK, 1],
  [ChoiceValue.LIZARD, ChoiceValue.LIZARD, 0],
];
