import { GameChoices } from "../../../../models/types";

export const playOptionsStub = [
  [GameChoices.Rock, GameChoices.Rock, 0],
  [GameChoices.Rock, GameChoices.Paper, -1],
  [GameChoices.Rock, GameChoices.Scissors, 1],
  [GameChoices.Rock, GameChoices.Spock, -1],
  [GameChoices.Rock, GameChoices.Lizard, 1],
  [GameChoices.Paper, GameChoices.Rock, 1],
  [GameChoices.Paper, GameChoices.Paper, 0],
  [GameChoices.Paper, GameChoices.Scissors, -1],
  [GameChoices.Paper, GameChoices.Spock, 1],
  [GameChoices.Paper, GameChoices.Lizard, -1],
  [GameChoices.Scissors, GameChoices.Rock, -1],
  [GameChoices.Scissors, GameChoices.Paper, 1],
  [GameChoices.Scissors, GameChoices.Scissors, 0],
  [GameChoices.Scissors, GameChoices.Spock, -1],
  [GameChoices.Scissors, GameChoices.Lizard, 1],
  [GameChoices.Spock, GameChoices.Rock, 1],
  [GameChoices.Spock, GameChoices.Paper, -1],
  [GameChoices.Spock, GameChoices.Scissors, 1],
  [GameChoices.Spock, GameChoices.Spock, 0],
  [GameChoices.Spock, GameChoices.Lizard, -1],
  [GameChoices.Lizard, GameChoices.Rock, -1],
  [GameChoices.Lizard, GameChoices.Paper, 1],
  [GameChoices.Lizard, GameChoices.Scissors, -1],
  [GameChoices.Lizard, GameChoices.Spock, 1],
  [GameChoices.Lizard, GameChoices.Lizard, 0],
];
