#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

printf "🕓 Run build packages\n"

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  if ! yarn build
  then
      printf "❌ ${RED} Failed to build: $PACKAGE \n"
      exit 1
  fi
  printf "✔ ${GREEN} Success, build package for: $PACKAGE \n"
done
