#!/bin/bash

export CUR=$(pwd)

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  echo "Run build packages for: $PACKAGE"

  if ! yarn build
  then
      echo "Failed to build: $PACKAGE"
      exit 1
  fi
done
