#!/bin/bash

export CUR=$(pwd)

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  echo "Run check test for: $PACKAGE"

  if ! yarn check-test
  then
      echo "Failed to check test for: $PACKAGE"
      exit 1
  fi
done
