#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

printf "🕓 Run check types for packages\n"

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  if ! yarn check-types
  then
      printf "❌ ${RED} Failed to check types for: $PACKAGE \n${NC}"
      exit 1
  fi
  printf "✔ ${GREEN} Success, check types for: $PACKAGE \n${NC}"
done
