#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  printf "${GREEN}Run check lint for: ${NC}$PACKAGE \n"

  if ! yarn check-lint
  then
      printf "${RED}Failed to lint: ${NC}$PACKAGE \n"
      exit 1
  fi
done
