#!/bin/bash

export CUR=$(pwd)

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  echo "Run check lint for: $PACKAGE"

  if ! yarn check-lint
  then
      echo "Failed to lint: $PACKAGE"
      exit 1
  fi
done
