#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

printf "🕓 Run check test changed for packages\n"

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  if ! yarn check-test-changed
  then
      printf "❌ ${RED} Failed to check test changed for: ${NC}$PACKAGE \n"
      exit 1
  fi
  printf "✔ ${GREEN} Success, check test changed for: ${NC}$PACKAGE \n"
done
