#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

printf "🕓 Run check lint for packages\n"

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  if ! yarn check-lint
  then
      printf "❌ ${RED} Failed to lint: $PACKAGE \n"
      exit 1
  fi
  printf "✔ ${GREEN} Success, check lint for: $PACKAGE \n"
done
