#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

printf "🕓 Run yarn install for packages\n"

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  if ! yarn install --silent
  then
      printf "❌ ${RED} Failed to install packages for: $PACKAGE \n"
      exit 1
  fi
  printf "✔ ${GREEN} Success, install packages for: $PACKAGE \n"
done
