#!/bin/bash

. "$(dirname "$0")/configs/colors"

CUR=$(pwd)

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  printf "${GREEN}Run yarn install for packages: ${NC}$PACKAGE \n"

  if ! yarn install --silent
  then
      printf "${RED}Failed to install packages for: ${NC}$PACKAGE \n"
      exit 1
  fi
done
