#!/bin/bash

. "$(dirname "$0")/_/husky.sh"

echo "Run pre-commit checks"

export CUR=$(pwd)

yarn check-lint-staged

for PACKAGE in $(ls ./packages)
do
  cd $CUR/packages/$PACKAGE

  yarn check-types
  yarn check-test-changed
done
