name: Validation
run-name: Validation ${{ github.ref_name }}

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install missing libssl1.1 package
        run: |
          chmod +x ./configs/scripts/workflows/install-container-packages
          ./configs/scripts/workflows/install-container-packages
        shell: bash

      - name: install dependencies
        run: yarn

      - name: Run type-check
        run: yarn check-types

      - name: Run linter
        run: yarn check-lint

      - name: Run tests
        run: yarn check-test

  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [18]

    runs-on: ${{ matrix.os }}

    needs: validation

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: install dependencies
        run: yarn

      - name: build
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          timeout_minutes: 10
          command: yarn build
          retry_on: error
