name: RPSLS feature branch
run-name: pushed ${{ github.actor }}

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
      - "!master"

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#     todo extract to separate action
      - name: Install missing libssl1.1 package
        run: |
          chmod +x ./configs/scripts/workflows/install-container-packages
          ./configs/scripts/workflows/install-container-packages
        shell: bash

      - name: install dependencies
        run: yarn

      - name: Run type-check
        run: yarn check-types

      - name: Run linter
        run: yarn check-lint

      - name: Run tests
        run: yarn check-test

  build:
    runs-on: ubuntu-latest
    needs: validation
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: yarn

      - name: build
        run: yarn build
