name: PR Cleanup
run-name:
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: 'Message to comment on stale PRs. If none provided, will not mark PRs stale'
          days-before-pr-stale: 45
          days-before-pr-close: 10
          exempt-pr-labels: 'DRAFT,WIP,WFA'
