name: PR Cleanup
run-name:
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: "Yo! m WIP branch! Not going to be commented or closed!"
          days-before-pr-stale: 1
          days-before-pr-close: 2
          exempt-pr-labels: "DRAFT,WIP,WFA"
